"""index incidents by creation time

Revision ID: b550434f6626
Revises: a7e280eb7b1e
Create Date: 2026-09-28 22:31:44.548144

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b550434f6626"
down_revision: str | Sequence[str] | None = "a7e280eb7b1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_incidents_created_at", "incidents", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_incidents_created_at", table_name="incidents")
    # ### end Alembic commands ###
